from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class XianShiYaoYueAssets:


	# Image Rule Assets
	# description 庭院右侧线下庆典入口(猫样式一)
	I_XY_OFFLINE_CELEBRATION = RuleImage(roi_front=(1184,379,44,45), roi_back=(1051,101,210,472), threshold=0.75, method="Template matching", file="./tasks/XianShiYaoYue/xy/xy_offline_celebration.png")
	# description 庭院右侧线下庆典入口(猫样式二)
	I_XY_OFFLINE_CELEBRATION_2 = RuleImage(roi_front=(1176,290,52,60), roi_back=(1051,101,210,472), threshold=0.75, method="Template matching", file="./tasks/XianShiYaoYue/xy/xy_offline_celebration_2.png")
	# description 右侧活动栏刷新按钮
	I_XY_REFRESH = RuleImage(roi_front=(1186,523,40,38), roi_back=(1150,460,130,140), threshold=0.75, method="Template matching", file="./tasks/XianShiYaoYue/xy/xy_refresh.png")
	# description 活动页检查-挑战地点标签
	I_XY_CHECK_ACTIVITY = RuleImage(roi_front=(178,134,160,42), roi_back=(100,100,400,150), threshold=0.8, method="Template matching", file="./tasks/XianShiYaoYue/xy/xy_check_activity.png")
	# description 左侧商店灯笼
	I_XY_GOTO_SHOP = RuleImage(roi_front=(101,291,68,104), roi_back=(60,250,180,200), threshold=0.8, method="Template matching", file="./tasks/XianShiYaoYue/xy/xy_goto_shop.png")
	# description 左侧活动灯笼-切换回活动页
	I_XY_GOTO_ACTIVITY = RuleImage(roi_front=(88,132,92,120), roi_back=(60,100,180,220), threshold=0.8, method="Template matching", file="./tasks/XianShiYaoYue/xy/xy_goto_activity.png")
	# description 左侧活动灯笼-商店页灰暗状态
	I_XY_GOTO_ACTIVITY_2 = RuleImage(roi_front=(102,143,81,114), roi_back=(60,100,180,220), threshold=0.8, method="Template matching", file="./tasks/XianShiYaoYue/xy/xy_goto_activity_2.png")
	# description 现世商店标题检查
	I_XY_CHECK_SHOP = RuleImage(roi_front=(520,45,270,67), roi_back=(400,20,500,120), threshold=0.8, method="Template matching", file="./tasks/XianShiYaoYue/xy/xy_check_shop.png")
	# description 寻找队伍按钮
	I_XY_FIND_TEAM = RuleImage(roi_front=(947,557,110,110), roi_back=(880,500,260,220), threshold=0.8, method="Template matching", file="./tasks/XianShiYaoYue/xy/xy_find_team.png")
	# description 自动匹配按钮
	I_XY_AUTO_MATCH = RuleImage(roi_front=(701,622,176,61), roi_back=(640,590,300,110), threshold=0.8, method="Template matching", file="./tasks/XianShiYaoYue/xy/xy_auto_match.png")
	# description 协战队伍挑战按钮
	I_XY_CHALLENGE = RuleImage(roi_front=(1160,580,108,96), roi_back=(1080,530,200,190), threshold=0.75, method="Template matching", file="./tasks/XianShiYaoYue/xy/xy_challenge.png")
	# description 排队横幅右上角X(排队中标志, 不可点击)
	I_XY_QUEUE_CLOSE = RuleImage(roi_front=(824,20,60,60), roi_back=(340,5,560,95), threshold=0.8, method="Template matching", file="./tasks/XianShiYaoYue/xy/xy_queue_close.png")
	# description 活动页组队挑战按钮(需虚拟定位)
	I_XY_TEAM_CHALLENGE = RuleImage(roi_front=(1102,558,96,99), roi_back=(1040,520,240,200), threshold=0.8, method="Template matching", file="./tasks/XianShiYaoYue/xy/xy_team_challenge.png")
	# description 队伍公开权限弹窗-创建按钮
	I_XY_CREATE = RuleImage(roi_front=(578,481,124,60), roi_back=(430,130,440,460), threshold=0.8, method="Template matching", file="./tasks/XianShiYaoYue/xy/xy_create_team.png")

	# Ocr Rule Assets
	# description 商店绿框区域现世祝福识别
	O_XY_BLESSING = RuleOcr(roi=(440,138,230,50), area=(440,138,230,50), mode="Single", method="Default", keyword="现世祝福", name="xy_blessing")
	# description 活动页挑战次数 38/40
	O_XY_BATTLE_COUNT = RuleOcr(roi=(990,680,170,32), area=(990,680,170,32), mode="DigitCounter", method="Default", keyword="", name="xy_battle_count")
	# description 排队横幅人数 前方约有1832排队
	O_XY_QUEUE = RuleOcr(roi=(440,50,280,48), area=(440,50,280,48), mode="Digit", method="Default", keyword="", name="xy_queue")

	# Click Rule Assets
	# description 点击现世祝福卡片
	C_XY_BLESSING = RuleClick(roi_front=(480,200,120,110), roi_back=(480,200,120,110), name="xy_blessing_click")
	# description 直接点击组队挑战
	C_XY_TEAM_CHALLENGE = RuleClick(roi_front=(1102,558,96,99), roi_back=(1102,558,96,99), name="xy_team_challenge_click")
	# description 勾选队伍公开权限-所有人
	C_XY_RADIO_ALL = RuleClick(roi_front=(506,262,44,46), roi_back=(506,262,44,46), name="xy_radio_all_click")

